Terting writing to script.log if error

diff --git a/.github/workflows/build-credential-files.yml b/.github/workflows/build-credential-files.yml
--- a/.github/workflows/build-credential-files.yml
+++ b/.github/workflows/build-credential-files.yml
@@ -53,12 +53,6 @@ jobs:
             echo "Validation log was not found."
          fi
 
-      - name: Fail workflow if validation failed
-        if: steps.validation.outcome == 'failure'
-        run: |
-         echo "Credential validation failed."
-         exit 1
-
       - name: Generate credential types
         run: node .github/scripts/build-credential-types-list.js
 
@@ -77,3 +71,9 @@ jobs:
       
           git commit -m "Auto update generated files [skip ci]" || echo "No changes"
           git push
+
+      - name: Fail workflow if validation failed
+        if: steps.validation.outcome == 'failure'
+        run: |
+         echo "Credential validation failed."
+         exit 1
